"""MBA RULES marker install + verifier (AC #7, AC #8)."""

from __future__ import annotations

from pathlib import Path

import pytest

from mba_foundation import markers


def test_count_markers_when_absent() -> None:
    counts = markers.count_markers("plain text\n")
    assert counts.begin_count == 0
    assert counts.end_count == 0


def test_count_markers_when_present() -> None:
    body = (
        "header\n\n"
        "<!-- BEGIN MBA RULES -->\nbody\n<!-- END MBA RULES -->\n"
    )
    counts = markers.count_markers(body)
    assert counts.begin_count == 1
    assert counts.end_count == 1
    assert counts.exactly_one_pair is True


def test_install_block_writes_when_file_absent(tmp_path: Path) -> None:
    target = tmp_path / "AGENTS.md"
    markers.install_block(target)
    text = target.read_text(encoding="utf-8")
    assert "<!-- BEGIN MBA RULES -->" in text
    assert "<!-- END MBA RULES -->" in text


def test_install_block_replaces_existing_block(tmp_path: Path) -> None:
    target = tmp_path / "AGENTS.md"
    target.write_text(
        "header\n<!-- BEGIN MBA RULES -->\nold body\n<!-- END MBA RULES -->\nfooter\n",
        encoding="utf-8",
    )
    markers.install_block(target)
    text = target.read_text(encoding="utf-8")
    assert "old body" not in text
    assert "MBA Foundation Rules" in text
    # Header and footer preserved around the block.
    assert text.startswith("header\n")
    assert "footer\n" in text


def test_install_block_appends_when_no_existing_block(tmp_path: Path) -> None:
    target = tmp_path / "AGENTS.md"
    target.write_text("existing content\n", encoding="utf-8")
    markers.install_block(target)
    text = target.read_text(encoding="utf-8")
    assert text.startswith("existing content\n")
    assert "<!-- BEGIN MBA RULES -->" in text


def test_beads_markers_remain_untouched_in_combined_file(tmp_path: Path) -> None:
    target = tmp_path / "AGENTS.md"
    target.write_text(
        "intro\n"
        "<!-- BEGIN BEADS INTEGRATION v:1 profile:minimal hash:abc -->\n"
        "beads body\n"
        "<!-- END BEADS INTEGRATION -->\n"
        "\n"
        "<!-- BEGIN BEADS CODEX SETUP: generated by bd setup codex -->\n"
        "codex body\n"
        "<!-- END BEADS CODEX SETUP -->\n",
        encoding="utf-8",
    )
    markers.install_block(target)
    text = target.read_text(encoding="utf-8")
    # Beads blocks remain unchanged.
    assert "<!-- BEGIN BEADS INTEGRATION v:1 profile:minimal hash:abc -->" in text
    assert "<!-- END BEADS INTEGRATION -->" in text
    assert "<!-- BEGIN BEADS CODEX SETUP: generated by bd setup codex -->" in text
    assert "<!-- END BEADS CODEX SETUP -->" in text
    # MBA block installed without disturbing them.
    assert "<!-- BEGIN MBA RULES -->" in text
    assert "<!-- END MBA RULES -->" in text


def test_block_content_carries_charter_reference() -> None:
    assert "docs/mba/charter.md" in markers.MBA_RULES_BLOCK
    assert "docs/beads/capabilities.md" in markers.MBA_RULES_BLOCK


def test_mba_rules_block_uses_module_form_for_first_contact() -> None:
    text = markers.MBA_RULES_BLOCK
    assert "python -m mba_runtime first-contact --cwd . --apply-setup" in text
    assert "mba-runtime first-contact --cwd ." not in text
    assert "optional shortcut" in text


def test_mba_rules_block_prefers_apply_setup() -> None:
    """The MBA RULES block steers the Orchestrator to the deterministic
    ``--apply-setup`` path so the setup handoff is not hand-written.

    Cold-start Orchestrators routinely skip the manual
    create-or-update + comment-write when prose is the only
    instruction; the embedded ``--apply-setup`` reference in the
    installed markers is the runtime-assisted default.
    """

    text = markers.MBA_RULES_BLOCK
    assert "--apply-setup" in text, (
        "MBA RULES block must reference --apply-setup so the "
        "installed instruction steers Orchestrators to the "
        "runtime-assisted setup handoff"
    )
    assert "--actor Orchestrator" in text


def test_mba_rules_block_requires_explicit_beads_write_actor() -> None:
    text = markers.MBA_RULES_BLOCK
    assert 'bd --actor "Orchestrator"' in text
    assert 'bd --actor "<Role>" comments add <id> -f <file>' in text
    assert "Never rely on the OS/Git/default actor" in text
    assert "Do not use ``bd update\n  --claim``" in text
    assert "bd comments add -t -" in text
    assert "||" in text and "head" in text and "wc" in text and "ls -la" in text
    assert 'bd --actor "Orchestrator" dep add' in text
    assert "rather than bare\n  ``bd dep add ...``" in text


def test_mba_rules_block_rejects_same_transcript_hat_switching() -> None:
    text = markers.MBA_RULES_BLOCK
    assert "One transcript changing hats is not a Doer/Auditor pair" in text
    assert "cannot launch or resume the required worker session" in text
    assert "does not manufacture\n  convergence inside the Orchestrator transcript" in text


def test_mba_rules_block_requires_observable_worker_launch_receipt() -> None:
    """The installed MBA RULES block must require an observable launch
    receipt for each Doer/Auditor session before any worker output is
    accepted. The Downstream smoke test showed MBA can ship Doer/Auditor
    artefacts without the worker sessions ever being launched
    separately, so the installed instructions must pin the launch.md
    fields and forbid treating the worker comment as proof the
    session existed.
    """

    import re

    text = markers.MBA_RULES_BLOCK
    assert ".mba-work/<bead-id>/<session-name>/launch.md" in text, (
        "MBA RULES block must point the Orchestrator at the launch "
        "receipt path so a downstream consumer cannot miss it"
    )
    # Field list — match with optional internal whitespace so line
    # breaks inside the format string don't break the test.
    for needle in (
        r"launch command shape",
        r"PID or session id",
        r"start time",
        r"model\s*/\s*AI\s*resource",
        r"prompt path",
        r"log\s*/\s*result paths",
    ):
        assert re.search(needle, text), f"MBA RULES block missing field: {needle!r}"
    # Without the receipt, the Orchestrator must not accept worker
    # outputs as proof the worker session existed.
    assert re.search(
        r"must not\s*treat a Bead comment as proof the session existed", text
    ), "MBA RULES block must forbid treating a Bead comment as proof the session existed"


def test_mba_rules_block_distinguishes_worker_internal_none_from_skipped_worker() -> None:
    """A worker comment line of ``worker-internal AI delegation: none``
    must be qualified to mean *the launched worker performed no
    further inner delegation*; it is not valid evidence that the
    worker session itself was launched. The Downstream smoke test allowed
    comments like ``Worker-internal AI delegation: none`` to be
    presented as proof of separate sessions when no separate session
    existed, so the installed MBA RULES block must forbid that
    substitution.
    """

    import re

    text = markers.MBA_RULES_BLOCK
    assert "Worker-internal AI delegation" in text
    # Mentions ``none`` as one of the legitimate delegation values.
    assert "``none``" in text
    # The clarification paragraph tells the reader ``none`` describes
    # inner delegation only and is not a substitute for the receipt.
    # Match with optional internal whitespace so line breaks in the
    # format string don't break the test.
    assert re.search(
        r"inside its own session after launch", text
    ), "MBA RULES block must say ``none`` describes inner delegation only"
    assert re.search(
        r"never\s+substitutes for the launch receipt", text
    ), "MBA RULES block must forbid treating ``none`` as a substitute for the launch receipt"
    assert re.search(
        r"no separate worker session was actually launched", text
    ), "MBA RULES block must say ``none`` must not be recorded when no separate worker session was launched"


def test_mba_rules_block_uses_safe_plain_worker_launch_pointer() -> None:
    text = markers.MBA_RULES_BLOCK
    assert "Put the full worker assignment in its ``prompt.md``" in text
    assert "only a short plain file pointer" in text
    assert "Never put Markdown\n  backticks, command examples, or rich assignment text" in text
    assert "PowerShell can interpret and corrupt it" in text
    assert "normally 4-16\n  non-blank lines" in text


def test_mba_rules_block_requires_launch_receipt_in_same_launch_step() -> None:
    """Downstream smoke test exposed that the prior wording allowed
    the Orchestrator to write the launch receipt **after** the
    worker produced `result.md` or a Bead comment. The installed MBA
    RULES block must require the receipt to be written **in the same
    launch step** that captures the worker's PID or session id, and
    **before** any wait / tail / read / acceptance of worker output.

    The test fails if the wording is weakened back to a bare
    "before accepting outputs" rule with no temporal ordering — that
    is exactly the wording the Downstream smoke test shipped.
    """

    import re

    text = markers.MBA_RULES_BLOCK
    # ``same launch step`` wording pins the temporal ordering.
    assert "same launch step" in text, (
        "MBA RULES block must require the launch receipt to be written "
        "in the same launch step that captures the worker's PID or "
        "session id (Downstream smoke test acceptance criterion)."
    )
    # ``before`` the wait/tail/read/acceptance — explicit list of what
    # is forbidden before the receipt is written.
    assert re.search(
        r"before[\s\S]{0,80}wait[\s\S]{0,80}tail[\s\S]{0,80}read[\s\S]{0,80}accept",
        text,
    ), (
        "MBA RULES block must list the wait/tail/read/accept steps "
        "that the Orchestrator must not perform before writing the "
        "launch receipt."
    )
    # Writing the receipt **after** worker output is a refusal-grade
    # error — the receipt no longer proves the session existed.
    assert "after" in text.lower() and "refusal-grade" in text.lower(), (
        "MBA RULES block must explicitly forbid writing the launch "
        "receipt after any worker output exists."
    )


def test_mba_rules_block_requires_hidden_windows_launch() -> None:
    """Downstream smoke test shipped empty CMD / conhost windows on the user
    desktop. The MBA RULES block must require hidden / background
    Windows launches by default and name ``-WindowStyle Hidden`` or
    the equivalent non-interactive background launcher."""

    import re

    text = markers.MBA_RULES_BLOCK
    assert "-WindowStyle Hidden" in text, (
        "MBA RULES block must pin the Windows hidden launch flag so a "
        "downstream consumer cannot regress to a visible empty CMD window."
    )
    assert "Start-Process" in text, (
        "MBA RULES block must name the Start-Process launcher pattern "
        "so an Orchestrator can copy-paste a safe shape."
    )
    assert "hidden" in text.lower() and "background" in text.lower(), (
        "MBA RULES block must say the worker launch is hidden and "
        "background by default."
    )
    assert "PassThru" in text, (
        "MBA RULES block must mention PassThru so the launch step "
        "captures the worker PID in the same step it writes the receipt."
    )
    assert "RedirectStandardOutput" in text and "RedirectStandardError" in text, (
        "MBA RULES block must require redirecting stdout / stderr so "
        "worker progress lives in the log files, not the desktop window."
    )


def test_mba_rules_block_says_empty_cmd_windows_are_not_progress_surface() -> None:
    """The Downstream smoke test exposed empty CMD / conhost windows as bad UX
    that carries no useful progress. The MBA RULES block must say so
    explicitly so a future Orchestrator cannot treat the visible empty
    window as evidence of work."""

    import re

    text = markers.MBA_RULES_BLOCK
    assert re.search(r"empty\s+CMD", text) or re.search(
        r"empty\s+desktop", text
    ), "MBA RULES block must mention the empty CMD / desktop window failure mode"
    assert re.search(
        r"not\s+(?:the\s+)?progress\s+surface", text
    ), "MBA RULES block must explicitly say the empty CMD window is not the progress surface"
    assert re.search(
        r"(?:logs|Bead\s+comments|launch\s+receipts)\s+are", text
    ), "MBA RULES block must name the actual progress surfaces (logs, Bead comments, launch receipts)"


def test_mba_rules_block_forbids_writing_receipt_after_worker_output() -> None:
    """Downstream smoke test shipped workers that produced ``report.md`` and
    Bead comments **before** the launch receipt existed. The MBA
    RULES block must explicitly forbid writing ``launch.md`` after
    any worker output (Bead comment, transcript, ``result.md``,
    ``report.md``) is present.
    """

    import re

    text = markers.MBA_RULES_BLOCK
    # Explicit forbidden-list of output kinds.
    for kind in ("Bead comment", "transcript", "result.md", "report.md"):
        assert kind in text, (
            f"MBA RULES block must name '{kind}' as part of the "
            "worker outputs that must not exist before launch.md is "
            "written."
        )
    # The phrase that pins the prohibition.
    assert re.search(
        r"after[\s\S]{0,40}any\s+worker\s+output", text
    ), "MBA RULES block must explicitly forbid writing launch.md after any worker output"
    assert re.search(
        r"refusal-grade\s+error", text
    ), "MBA RULES block must call writing the receipt after worker output a refusal-grade error"


def test_mba_rules_block_requires_visible_headless_handoff_and_identity_proof() -> None:
    """Pin the visible headless Orchestrator handoff (status ``blocked``,
    assignee ``Human``, ``human`` label) and the launch-receipt identity
    proof rule. Uses whitespace-flexible regexes so the canonical
    ``MBA_RULES_BLOCK`` can wrap at ~75 chars without breaking the test
    (the F2 fix).
    """

    import re

    text = markers.MBA_RULES_BLOCK
    assert "Hidden, headless, and non-interactive Orchestrators" in text
    assert "only in their transcript" in text
    # The handoff phrases used to be brittle contiguous-`in` assertions
    # that forced the block onto a single 210-char line. Match with
    # optional whitespace so line wrapping is unconstrained.
    for needle in (
        r"post(?:s)?\s+a\s+structured\s+Bead\s+comment",
        r"set(?:s)?\s+status\s+``blocked``",
        r"assign(?:s)?\s+``Human``",
        r"add(?:s)?\s+the\s+``human``\s+label",
    ):
        assert re.search(needle, text), (
            f"MBA RULES block missing handoff phrase: {needle!r}"
        )
    assert "PID-only proof is not" in text
    assert "differs from the Orchestrator" in text
    assert "``report.md`` / ``comment.md`` is still missing" in text
    assert "fresh launch receipt" in text


def test_mba_rules_block_rejects_internal_subagent_as_mba_worker() -> None:
    """Regression for ``example-comments`` F3: the host's built-in subagent
    surface (OpenCode's internal ``task`` tool, the ``General Agent``
    subagent, any "delegate to another model" facility) is NOT an MBA
    worker. The MBA RULES block shipped into every consumer's
    ``AGENTS.md`` / ``CLAUDE.md`` must say so explicitly so a future
    edit cannot silently drop the rule (the Downstream smoke test gap this bead
    closes).
    """

    import re

    text = markers.MBA_RULES_BLOCK
    # The rule must be present and call the surface out by name.
    assert re.search(
        r"host's built-in subagent surface", text
    ), "MBA RULES block must name the host's built-in subagent surface"
    assert "OpenCode's internal ``task``" in text, (
        "MBA RULES block must name OpenCode's internal ``task`` tool"
        " so the reader cannot mistake a built-in subagent for an MBA worker"
    )
    assert "``General Agent``" in text, (
        "MBA RULES block must name the General Agent subagent"
    )
    # The negative verdict is the load-bearing phrase. The reader can
    # match across multiple lines so the wrap distance is generous.
    assert re.search(
        r"subagent surface[\s\S]{0,200}is\s+\*\*not\*\*\s+an\s+MBA\s+worker",
        text,
    ), "MBA RULES block must say the subagent surface is not an MBA worker"
    # The rule must also explain why (shared transcript, no launch receipt).
    assert re.search(
        r"share[\s\S]{0,40}Orchestrator transcript", text
    ), "MBA RULES block must explain internal subagents share the Orchestrator transcript"
    assert ".mba-work/<bead-id>/<session-name>/launch.md" in text and (
        re.search(
            r"never\s+write[\s\S]{0,80}\.mba-work", text
        )
    ), (
        "MBA RULES block must note that internal subagents never write "
        "the MBA launch receipt"
    )
    # The canonical MBA worker surface on Windows / OpenCode is the
    # external `opencode run --agent mba-worker` worker.
    assert re.search(
        r"external\s+``opencode\s+run\s+--agent\s+mba-worker``\s+process",
        text,
    ), (
        "MBA RULES block must name `opencode run --agent mba-worker` "
        "as the external MBA worker surface"
    )
    assert "bare ``opencode`` PowerShell shim" in text
    assert re.search(r"wrapper\s+``cmd\.exe``\s+PID", text)


def test_mba_rules_block_forbids_routine_kickoff_comment() -> None:
    """Regression for ``example-comments`` F3: the Orchestrator does NOT post a
    routine kickoff comment just to mark "work started". The launch
    receipt and the worker's own role-attributed comment are the
    normal progress surface; a kickoff Bead comment adds no
    information and burns an audit row.
    """

    import re

    text = markers.MBA_RULES_BLOCK
    # The phrase that pins the rule.
    assert re.search(
        r"does\s+\*\*not\*\*\s+post\s+a\s+routine\s+kickoff\s+comment", text
    ), (
        "MBA RULES block must explicitly say the Orchestrator does not "
        "post a routine kickoff comment"
    )
    # The replacement (launch receipt + worker comment) must be named
    # so the reader knows what the progress surface is instead.
    assert re.search(
        r"launch\s+receipt", text
    ) and re.search(
        r"worker(?:'s)?\s+own\s+(?:role[\-\s]attributed\s+)?comment", text
    ), "MBA RULES block must name the launch receipt and worker comment as the progress surface"
    # And it must explain the harm (extra audit row, no information).
    assert re.search(
        r"burns?\s+an\s+audit\s+row", text
    ), "MBA RULES block must explain why a kickoff comment is wasteful"


def test_mba_rules_block_forbids_bulky_evidence_and_static_repeat_in_comments() -> None:
    """Regression for ``example-comments`` F3: Bead comments must not paste
    worker transcripts / prompts / other bulky evidence, and must not
    repeat static / implicit Bead fields just to fill lines. Both
    rules must hold in the installed MBA RULES block so the same
    canonical text guards every consumer's ``AGENTS.md``.
    """

    import re

    text = markers.MBA_RULES_BLOCK
    # No bulky-evidence paste rule.
    assert re.search(
        r"Do\s+not\s+paste\s+worker\s+transcripts?,?\s+prompts?,?\s+or\s+other\s+bulky\s+evidence",
        text,
    ), "MBA RULES block must forbid pasting worker transcripts/prompts/bulky evidence into Bead comments"
    # Redirects the bulky evidence to the on-disk path.
    assert ".mba-work/<bead-id>/<session-name>/" in text, (
        "MBA RULES block must redirect bulky evidence to .mba-work/<bead-id>/<session-name>/"
    )
    assert re.search(
        r"placeholder\s+file", text
    ), "MBA RULES block must say the comment must not link placeholder files"
    # No static-repeat rule.
    assert re.search(
        r"[Nn]ever\s+repeat\s+static\s*/\s*implicit\s+Bead\s+fields", text
    ), "MBA RULES block must forbid repeating static / implicit Bead fields in comments"


def test_canonical_tail_is_html_comment_close() -> None:
    assert markers.MBA_RULES_BLOCK.rstrip().endswith("<!-- END MBA RULES -->")




def test_beads_markers_assertion_passes_when_present(tmp_path: Path) -> None:
    target = tmp_path / "AGENTS.md"
    target.write_text(
        "<!-- BEGIN BEADS INTEGRATION v:1 profile:minimal hash:abc -->\n"
        "body\n"
        "<!-- END BEADS INTEGRATION -->\n"
        "\n"
        "<!-- BEGIN BEADS CODEX SETUP: generated by bd setup codex -->\n"
        "body\n"
        "<!-- END BEADS CODEX SETUP -->\n",
        encoding="utf-8",
    )
    ok, reason = markers.assert_beads_markers_untouched(target)
    assert ok is True, reason


def test_beads_markers_assertion_fails_when_marker_missing(tmp_path: Path, monkeypatch) -> None:
    target = tmp_path / "AGENTS.md"
    # Establish the baseline first by running the check on the
    # pristine file (which has INTEGRATION + CODEX SETUP).
    target.write_text(
        "<!-- BEGIN BEADS INTEGRATION v:1 profile:minimal hash:abc -->\n"
        "body\n"
        "<!-- END BEADS INTEGRATION -->\n"
        "\n"
        "<!-- BEGIN BEADS CODEX SETUP: generated by bd setup codex -->\n"
        "body\n"
        "<!-- END BEADS CODEX SETUP -->\n",
        encoding="utf-8",
    )
    monkeypatch.chdir(tmp_path)
    # Confine the baseline carrier to ``tmp_path`` so this test never
    # touches the active repository's baseline file (the
    # ``example-008.1`` fix correctly walks up to the project's ``.git/``).
    monkeypatch.setattr(markers, "_find_repo_cwd", lambda _p: tmp_path)
    # First call captures the baseline.
    markers.assert_beads_markers_untouched(target)

    # Now delete the CODEX SETUP block; the check must fail with the
    # new line-anchored form.
    target.write_text(
        "<!-- BEGIN BEADS INTEGRATION v:1 profile:minimal hash:abc -->\n"
        "body\n"
        "<!-- END BEADS INTEGRATION -->\n",
        encoding="utf-8",
    )
    ok, reason = markers.assert_beads_markers_untouched(target)
    assert ok is False
    assert "BEADS CODEX SETUP" in reason
    assert "begin=" in reason and "end=" in reason


def test_beads_markers_substring_false_positive_caught(tmp_path: Path, monkeypatch) -> None:
    """F1 regression: a file that mentions marker names in prose but
    has never had a Beads-generated marker must NOT be flagged as
    "untouched violation" — the per-file baseline lets it pass.
    """

    target = tmp_path / "CLAUDE.md"
    # This content quotes the Beads marker names in Markdown text but
    # never writes them as a real `<!-- BEGIN ... -->` boundary line.
    target.write_text(
        "# Notes\n\n"
        "The blocks ``<!-- BEGIN BEADS INTEGRATION -->`` and "
        "``<!-- END BEADS CODEX SETUP -->`` are referenced for "
        "documentation.\n"
        "<!-- BEGIN MBA RULES -->\nbody\n<!-- END MBA RULES -->\n",
        encoding="utf-8",
    )
    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(markers, "_find_repo_cwd", lambda _p: tmp_path)
    ok, reason = markers.assert_beads_markers_untouched(target)
    # First contact: capture baseline. The baseline will record that
    # no Beads-generated blocks were present, so the check passes.
    assert ok is True, reason


def test_baseline_persists_across_invocations(tmp_path: Path, monkeypatch) -> None:
    target = tmp_path / "AGENTS.md"
    target.write_text(
        "<!-- BEGIN BEADS INTEGRATION v:1 profile:minimal hash:abc -->\n"
        "body\n"
        "<!-- END BEADS INTEGRATION -->\n"
        "\n"
        "<!-- BEGIN BEADS CODEX SETUP: generated by bd setup codex -->\n"
        "body\n"
        "<!-- END BEADS CODEX SETUP -->\n",
        encoding="utf-8",
    )
    monkeypatch.chdir(tmp_path)
    # Confine the baseline carrier to ``tmp_path`` (see
    # ``example-008.1`` fix).
    monkeypatch.setattr(markers, "_find_repo_cwd", lambda _p: tmp_path)
    markers.assert_beads_markers_untouched(target)
    baseline_path = tmp_path / ".mba-work" / ".marker-baseline.json"
    assert baseline_path.exists()


def test_baseline_captures_only_present_families(tmp_path: Path, monkeypatch) -> None:
    """A file with only INTEGRATION (no CODEX SETUP) records only
    INTEGRATION; future checks do not complain about CODEX SETUP.
    """

    target = tmp_path / "CLAUDE.md"
    target.write_text(
        "<!-- BEGIN BEADS INTEGRATION v:1 profile:minimal hash:abc -->\n"
        "body\n"
        "<!-- END BEADS INTEGRATION -->\n",
        encoding="utf-8",
    )
    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(markers, "_find_repo_cwd", lambda _p: tmp_path)
    markers.assert_beads_markers_untouched(target)

    # Even if we add prose referencing the CODEX SETUP marker, no
    # violation should occur.
    target.write_text(
        "<!-- BEGIN BEADS INTEGRATION v:1 profile:minimal hash:abc -->\n"
        "body\n"
        "<!-- END BEADS INTEGRATION -->\n"
        "\n"
        "Note about ``<!-- BEGIN BEADS CODEX SETUP -->``.\n",
        encoding="utf-8",
    )
    ok, reason = markers.assert_beads_markers_untouched(target)
    assert ok is True, reason


def test_baseline_records_missing_marker_after_deletion(tmp_path: Path, monkeypatch) -> None:
    """If a baseline was captured with a marker present, and the marker
    is later removed, the check fails with the labelled missing family.
    """

    target = tmp_path / "AGENTS.md"
    target.write_text(
        "<!-- BEGIN BEADS INTEGRATION v:1 profile:minimal hash:abc -->\n"
        "body\n"
        "<!-- END BEADS INTEGRATION -->\n"
        "\n"
        "<!-- BEGIN BEADS CODEX SETUP: generated by bd setup codex -->\n"
        "body\n"
        "<!-- END BEADS CODEX SETUP -->\n",
        encoding="utf-8",
    )
    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(markers, "_find_repo_cwd", lambda _p: tmp_path)
    markers.assert_beads_markers_untouched(target)

    target.write_text(
        "<!-- BEGIN BEADS INTEGRATION v:1 profile:minimal hash:abc -->\n"
        "body\n"
        "<!-- END BEADS INTEGRATION -->\n",
        encoding="utf-8",
    )
    ok, reason = markers.assert_beads_markers_untouched(target)
    assert ok is False
    assert "BEADS CODEX SETUP" in reason


def test_reset_baseline_re_captures(tmp_path: Path, monkeypatch) -> None:
    target = tmp_path / "AGENTS.md"
    target.write_text(
        "<!-- BEGIN BEADS INTEGRATION v:1 profile:minimal hash:abc -->\n"
        "body\n"
        "<!-- END BEADS INTEGRATION -->\n",
        encoding="utf-8",
    )
    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(markers, "_find_repo_cwd", lambda _p: tmp_path)
    markers.assert_beads_markers_untouched(target)
    markers.reset_baseline(tmp_path)
    # After reset, no baseline file exists.
    baseline_path = tmp_path / ".mba-work" / ".marker-baseline.json"
    assert not baseline_path.exists()
    # Re-running captures fresh.
    markers.assert_beads_markers_untouched(target)
    assert baseline_path.exists()


def test_find_repo_cwd_does_not_latch_onto_ancestor_pollution(
    tmp_path: Path,
) -> None:
    """``example-008.1`` regression: the upward walk must NOT return an
    ancestor that owns a stray ``.mba-work/``.

    The previous ``_find_repo_cwd`` returned the first ancestor with
    ``.mba-work/``, ``.beads/`` or ``.git/``. A stray ``.mba-work/``
    outside the active project (the ``C:\\.mba-work`` pollution from
    the ``example-007.1`` boundary incident) therefore captured the
    baseline and caused a write outside the active repository. The
    fix reorders the boundary checks: ``.git/`` first, ``.beads/``
    second, otherwise return the file's parent.

    The test runs under the prescribed repository-local
    ``--basetemp`` so ``tmp_path`` lives under the active
    repository's ``.git/`` boundary. With the fix the walk stops at
    that boundary (the project root) and never reaches the
    ``tmp_path`` ancestor that owns the pollution. Pre-fix code
    would have visited ``ancestor_dir`` and latched onto its
    ``.mba-work/`` pollution.
    """

    ancestor = tmp_path / "ancestor_dir"
    active = ancestor / "active_repo"
    ancestor.mkdir()
    active.mkdir()
    # The sandbox has NO ``.git/`` and NO ``.beads/`` so without the
    # fix the walk would have to keep climbing past ``ancestor_dir``.
    assert not (active / ".git").exists()
    assert not (active / ".beads").exists()

    pollution = ancestor / ".mba-work" / ".marker-baseline.json"
    pollution_payload = (
        '{"ancestor/AGENTS.md": ["BEADS INTEGRATION"]}\n'
    )
    pollution.parent.mkdir(parents=True, exist_ok=True)
    pollution.write_text(pollution_payload, encoding="utf-8")

    target = active / "AGENTS.md"
    target.write_text(
        "<!-- BEGIN BEADS INTEGRATION v:1 profile:minimal hash:abc -->\n"
        "body\n"
        "<!-- END BEADS INTEGRATION -->\n",
        encoding="utf-8",
    )

    result = markers._find_repo_cwd(target)
    # The walk must NOT have returned the ancestor (which owns the
    # pollution). With the fix the walk climbs past ``ancestor_dir``
    # until it reaches the active repository's ``.git/`` and returns
    # that. Without the fix the walk would have returned
    # ``ancestor_dir`` and the test below would fail.
    assert result != ancestor, (
        f"_find_repo_cwd returned ancestor {ancestor}; "
        "the walk latched onto pollution. The example-008.1 fix should "
        "have stopped the walk at the active project's .git/."
    )


def test_assert_beads_markers_untouched_preserves_ancestor_pollution(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """``example-008.1`` integration: a stray ``.mba-work/`` outside the
    confined baseline carrier is NOT touched by
    ``assert_beads_markers_untouched``.

    Pins ``_find_repo_cwd`` to ``active`` so the baseline carrier is
    local to the test sandbox; this isolates the integration check
    from the project-root walk-up exercised separately by
    ``test_find_repo_cwd_does_not_latch_onto_ancestor_pollution``.
    """

    ancestor = tmp_path / "ancestor_dir"
    active = ancestor / "active_repo"
    ancestor.mkdir()
    active.mkdir()

    pollution = ancestor / ".mba-work" / ".marker-baseline.json"
    pollution_payload = (
        '{"ancestor/AGENTS.md": ["BEADS INTEGRATION"]}\n'
    )
    pollution.parent.mkdir(parents=True, exist_ok=True)
    pollution.write_text(pollution_payload, encoding="utf-8")

    target = active / "AGENTS.md"
    target.write_text(
        "<!-- BEGIN BEADS INTEGRATION v:1 profile:minimal hash:abc -->\n"
        "body\n"
        "<!-- END BEADS INTEGRATION -->\n",
        encoding="utf-8",
    )

    # Confine the baseline carrier to ``active``.
    monkeypatch.setattr(markers, "_find_repo_cwd", lambda _p: active)

    ok, reason = markers.assert_beads_markers_untouched(target)
    assert ok is True, reason

    # Baseline lives inside the confined active repo, not the ancestor.
    fresh_baseline = active / ".mba-work" / ".marker-baseline.json"
    assert fresh_baseline.exists(), (
        "baseline was not captured inside the confined active repo"
    )

    # The ancestor pollution MUST be byte-for-byte preserved.
    assert pollution.read_text(encoding="utf-8") == pollution_payload


def test_find_repo_cwd_returns_active_repo_when_git_present(
    tmp_path: Path,
) -> None:
    """``example-008.1`` regression: when the active repo owns ``.git/``
    and an ancestor has a stray ``.mba-work/``, the walk stops at
    the active repo's ``.git/`` boundary.

    This is the typical real-world shape
    (``C:\\CODE\\MultipleBeadedAgents`` has ``.git/``); the fix
    reorders the boundary checks so the active repo's ``.git/``
    wins over any ancestor pollution.
    """

    ancestor = tmp_path / "ancestor_dir"
    active = ancestor / "active_repo"
    ancestor.mkdir()
    active.mkdir()
    (active / ".git").mkdir()

    pollution = ancestor / ".mba-work" / ".marker-baseline.json"
    pollution_payload = (
        '{"ancestor/AGENTS.md": ["BEADS INTEGRATION"]}\n'
    )
    pollution.parent.mkdir(parents=True, exist_ok=True)
    pollution.write_text(pollution_payload, encoding="utf-8")

    target = active / "AGENTS.md"
    target.write_text(
        "<!-- BEGIN BEADS INTEGRATION v:1 profile:minimal hash:abc -->\n"
        "body\n"
        "<!-- END BEADS INTEGRATION -->\n",
        encoding="utf-8",
    )

    result = markers._find_repo_cwd(target)
    assert result == active, (
        f"expected the walk to stop at the active repo {active}, "
        f"got {result}"
    )
    assert pollution.read_text(encoding="utf-8") == pollution_payload
