"""`bd version` preflight + capability-record conformance check.

Acceptance row coverage (Foundation AC #1, AC #2):

* Run ``bd version`` at the start of every MBA run, capture the value,
  write it to ``.mba-work/<bead>/orchestrator/working.md``, and use it
  to gate every subsequent Bead write. (`docs/mba/charter.md` §10 +
  ``docs/beads/capabilities.md`` Version policy.)
* Compare the recorded version to the validated set (``bd 1.0.4``) and
  refuse to proceed on mismatch. (capabilities.md Version policy.)
"""

from __future__ import annotations

import json
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

from .constants import BD_VERSION_PATTERN, VALIDATED_BD_VERSIONS


@dataclass(frozen=True)
class PreflightResult:
    """Outcome of the `bd version` preflight + capability check."""

    bd_version: str | None          # `1.0.4` on success, None if `bd` absent.
    raw_output: str                 # stdout of `bd version` verbatim.
    matches_record: bool            # False ⇢ refuse to proceed on this evidence.
    validated_versions: tuple[str, ...]
    reason: str                     # Empty on success; failure explanation otherwise.

    @property
    def ok(self) -> bool:
        return self.bd_version is not None and self.matches_record


def run_bd_version(bd_binary: str = "bd", cwd: Path | None = None) -> str:
    """Run ``bd version`` and return raw stdout.

    Raises ``FileNotFoundError`` when the binary is missing so callers can
    surface a clear, refusal-grade failure rather than a stack trace.
    """

    proc = subprocess.run(
        [bd_binary, "version"],
        capture_output=True,
        text=True,
        check=False,
        cwd=str(cwd) if cwd is not None else None,
    )
    if proc.returncode != 0:
        raise FileNotFoundError(
            f"`{bd_binary} version` exited {proc.returncode}; "
            f"stderr={proc.stderr.strip()!r}"
        )
    return (proc.stdout or "").strip()


def extract_bd_version(raw_output: str) -> str | None:
    """Pull the leading semver token from ``bd version`` stdout."""

    if not raw_output:
        return None
    match = BD_VERSION_PATTERN.search(raw_output)
    return match.group(1) if match else None


def capability_conformance_check(
    bd_version: str | None,
    *,
    validated_versions: frozenset[str] = VALIDATED_BD_VERSIONS,
) -> tuple[bool, str]:
    """Compare a recorded `bd` version against the validated set.

    Returns ``(matches, reason)``. ``matches=False`` triggers a refusal to
    proceed (see ``docs/beads/capabilities.md`` Version policy: "MBA never
    silently upgrades or switches the tool").
    """

    if bd_version is None:
        return False, "recorded `bd` version is None; preflight did not run"
    if bd_version in validated_versions:
        return True, ""
    sorted_validated = ", ".join(sorted(validated_versions))
    return False, (
        f"recorded `bd` version {bd_version!r} is not in the validated set "
        f"({sorted_validated!r}). Per capabilities.md Version policy, MBA "
        f"refuses to proceed without (a) revalidation evidence and (b) user "
        f"approval per docs/mba/charter.md §11."
    )


def preflight(
    *,
    bead_id: str,
    orchestrator_dir: Path,
    bd_binary: str = "bd",
    cwd: Path | None = None,
    validated_versions: frozenset[str] = VALIDATED_BD_VERSIONS,
) -> PreflightResult:
    """Run the full preflight and persist the evidence.

    The captured value is written to
    ``<orchestrator_dir>/working.md`` (a JSON preamble) and the raw
    ``bd version`` output is captured next to it. The Bead's
    orchestrator-level working record is the durable gate for every
    subsequent Bead write in the same run.
    """

    try:
        raw = run_bd_version(bd_binary=bd_binary, cwd=cwd)
    except FileNotFoundError as exc:
        return PreflightResult(
            bd_version=None,
            raw_output=str(exc),
            matches_record=False,
            validated_versions=tuple(sorted(validated_versions)),
            reason=f"`{bd_binary}` binary is unavailable: {exc}",
        )

    version = extract_bd_version(raw)
    matches, reason = capability_conformance_check(
        version, validated_versions=validated_versions
    )

    orchestrator_dir.mkdir(parents=True, exist_ok=True)
    working_path = orchestrator_dir / "working.md"
    payload: dict[str, object] = {
        "bead_id": bead_id,
        "bd_version": version,
        "raw_bd_version_output": raw,
        "validated_versions": sorted(validated_versions),
        "matches_record": matches,
        "reason": reason,
    }
    working_path.write_text(
        "<!-- auto-generated by mba_foundation.preflight.preflight -->\n"
        "```json\n"
        + json.dumps(payload, indent=2, sort_keys=True)
        + "\n```\n",
        encoding="utf-8",
    )

    return PreflightResult(
        bd_version=version,
        raw_output=raw,
        matches_record=matches,
        validated_versions=tuple(sorted(validated_versions)),
        reason=reason,
    )


_REFUSAL_BANNER = re.compile(r"\b(refuse|refusing)\b", re.IGNORECASE)
